---

- import_tasks: user.yml

- import_tasks: postgresql.yml
  when: not patroni_postgresql_exists

- name: Install system packages for patroni
  package:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
    update_cache: yes
  with_items:
    - "{{ patroni_system_packages }}"

- name: apt | install requirements
  apt:
    name: "{{item}}"
    state: present
  with_items:
    - git
    - python3-urllib3
    - python3-boto
    - python3-psycopg2
    - python3-yaml
    - python3-requests
    - python3-six
    - python3-kazoo
    - python3-click
    - python3-prettytable
    - python3-tzlocal
    - python3-dateutil
    - python3-psutil
    - python3-dnspython
    - python3-ruamel.yaml
    - python3-pip
    - libnss-resolve
  tags:
    - patronictl

- name: pip install cdiff
  pip:
    name: cdiff
  tags:
    - patronictl

- name: Install pip packages for patroni
  pip:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
    umask: "{{ item.umask }}"
  with_items:
    - "{{ patroni_pip_packages }}"
