---

- name: Include OS-specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- block:
  - name: install ius repo
    yum:
      name: "{{ item }}"
      state: present
    loop: 
      - "{{ repo_list }}"

  - name: install haproxy
    yum: 
      name: "{{ haproxy_pkg }}"
      state: present
  when: ansible_os_family == "RedHat"
  
- name: place haproxy.cfg
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: 0644
    owner: root
    group: root
  notify: reload_haproxy



- name: Ensure haproxy is running
  systemd:
    name: haproxy.service
    state: started
    daemon_reload: yes
    enabled: yes

