---
- hosts: consul
  become: yes
  vars_files:
    - vars/default.yml
    - vars/{{env}}.yml
  serial:
    - 3
    - 100%

  roles:
    - { role: consul_server, when: "inventory_hostname in groups ['consul_server']", tags: ['consul_server'] }

- hosts: consul
  become: yes

  vars_files:
    - vars/default.yml
    - vars/{{env}}.yml
  serial:
    - 3
    - 100%

  roles:
    - { role: common, when: "inventory_hostname in groups ['consul_patroni']|default([])" }
    - { role: patroni_consul, when: "inventory_hostname in groups ['consul_patroni']|default([])", tags: ['patroni_consul'] }
    - { role: consul_exporter, when: "inventory_hostname in groups ['consul_patroni']|default([])", tags: ['consul_exporter'] }
    - { role: create_db, when: "inventory_hostname in groups ['consul_patroni']|default([])", tags: ['create_db'],ansible_python_interpreter: "/usr/bin/python3"  }
    - { role: haproxy, when: "inventory_hostname in groups ['consul_patroni']|default([])", tags: ['haproxy']  }
    - { role: keepalived, when: "inventory_hostname in groups ['consul_patroni']|default([])", tags: ['keepalived']  }
    - { role: tuning_os, when: "inventory_hostname in groups ['consul_patroni']|default([])", tags: ['tuning_os']  }
    - { role: transpanent_pages, when: "inventory_hostname in groups ['consul_patroni']|default([])", tags: ['transpanent_pages'] }
