---

- name: Add consul group
  group:
    name: "{{ consul_system_group }}"
    state: present

- name: Add consul user
  user:
    name: "{{ consul_system_user }}"
    group: "{{ consul_system_group }}"
    system: yes
