---

- name: Install depends keepalived packages
  package:
    name: "{{ item }}"
    state: present
  loop:
    - gcc
    - kernel-headers
    - kernel-devel

- name: install keepalived
  package:
    name: keepalived
    state: present

- name: place keepalived config
  template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
    mode: 0644
    owner: root
    group: root

- name: Ensure keepalived is running
  systemd:
    name: keepalived.service
    state: started
    daemon_reload: yes
    enabled: yes



